spring:
  port: 8888

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strategy: com.joking.strategy.TenantDatabaseSelectorStrategy
      datasource:
        master:
          url: jdbc:mysql://pre-cluster2-rw-mysql.lepudigital.com:33185/lepu_market?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
          username: dev
          password: Devu3er-
          driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
          min-idle: 10
          max-wait: 6000
          max-active: 100
          initial-size: 10
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 10
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          keep-alive: false
          filters: stat
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          stat-view-servlet:
            enabled: true
            allow: 127.0.0.1
            login-username: lepu_user
            login-password: G!@a
            url-pattern: /druid/*
